/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SubscriptionManager {
  export type PackageStruct = {
    id: BigNumberish;
    title: string;
    price: BigNumberish;
    channelCount: BigNumberish;
    creator: AddressLike;
    active: boolean;
    subscriberCount: BigNumberish;
    createdAt: BigNumberish;
  };

  export type PackageStructOutput = [
    id: bigint,
    title: string,
    price: bigint,
    channelCount: bigint,
    creator: string,
    active: boolean,
    subscriberCount: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    title: string;
    price: bigint;
    channelCount: bigint;
    creator: string;
    active: boolean;
    subscriberCount: bigint;
    createdAt: bigint;
  };

  export type SubscriptionStruct = {
    packageId: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    autoRenew: boolean;
    tokenId: BigNumberish;
    totalPaid: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    packageId: bigint,
    startTime: bigint,
    endTime: bigint,
    autoRenew: boolean,
    tokenId: bigint,
    totalPaid: bigint
  ] & {
    packageId: bigint;
    startTime: bigint;
    endTime: bigint;
    autoRenew: boolean;
    tokenId: bigint;
    totalPaid: bigint;
  };
}

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addChannelToPackage"
      | "approve"
      | "balanceOf"
      | "cancelAutoRenewal"
      | "createPackage"
      | "creatorEarnings"
      | "getAllActivePackages"
      | "getApproved"
      | "getCreatorPackages"
      | "getPackageChannels"
      | "getSubscriptionInfo"
      | "getTotalEarnings"
      | "getUserSubscriptions"
      | "hasActiveSubscription"
      | "isApprovedForAll"
      | "name"
      | "owner"
      | "ownerOf"
      | "packageCount"
      | "packages"
      | "pause"
      | "paused"
      | "platformFee"
      | "renewSubscription"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setPlatformFee"
      | "setTreasury"
      | "subscribe"
      | "subscriptions"
      | "supportsInterface"
      | "symbol"
      | "togglePackageStatus"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateChannelInPackage"
      | "updatePackage"
      | "withdrawAllEarnings"
      | "withdrawEarnings"
      | "withdrawTreasuryFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "EarningsWithdrawn"
      | "OwnershipTransferred"
      | "PackageCreated"
      | "PackageStatusChanged"
      | "PackageUpdated"
      | "Paused"
      | "PlatformFeeUpdated"
      | "Subscribed"
      | "SubscriptionCancelled"
      | "SubscriptionRenewed"
      | "Transfer"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addChannelToPackage",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAutoRenewal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPackage",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllActivePackages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorPackages",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPackageChannels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionInfo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveSubscription",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "packageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "packages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renewSubscription",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "togglePackageStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateChannelInPackage",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePackage",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTreasuryFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addChannelToPackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAutoRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllActivePackages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorPackages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPackageChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packages", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renewSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "togglePackageStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateChannelInPackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTreasuryFees",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [
    creator: AddressLike,
    packageId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    packageId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    creator: string;
    packageId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackageCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    title: string,
    price: BigNumberish,
    creator: AddressLike,
    channelCount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    title: string,
    price: bigint,
    creator: string,
    channelCount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    title: string;
    price: bigint;
    creator: string;
    channelCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackageStatusChangedEvent {
  export type InputTuple = [id: BigNumberish, active: boolean];
  export type OutputTuple = [id: bigint, active: boolean];
  export interface OutputObject {
    id: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackageUpdatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    newPrice: BigNumberish,
    newChannelCount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    newPrice: bigint,
    newChannelCount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    newPrice: bigint;
    newChannelCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    user: AddressLike,
    packageId: BigNumberish,
    durationMonths: BigNumberish,
    endTime: BigNumberish,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    packageId: bigint,
    durationMonths: bigint,
    endTime: bigint,
    tokenId: bigint
  ];
  export interface OutputObject {
    user: string;
    packageId: bigint;
    durationMonths: bigint;
    endTime: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [user: AddressLike, packageId: BigNumberish];
  export type OutputTuple = [user: string, packageId: bigint];
  export interface OutputObject {
    user: string;
    packageId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    packageId: BigNumberish,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    packageId: bigint,
    newEndTime: bigint
  ];
  export interface OutputObject {
    user: string;
    packageId: bigint;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addChannelToPackage: TypedContractMethod<
    [packageId: BigNumberish, channel: string],
    [void],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  cancelAutoRenewal: TypedContractMethod<
    [packageId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPackage: TypedContractMethod<
    [title: string, pricePerMonth: BigNumberish, channelCount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  creatorEarnings: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getAllActivePackages: TypedContractMethod<
    [],
    [SubscriptionManager.PackageStructOutput[]],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCreatorPackages: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getPackageChannels: TypedContractMethod<
    [packageId: BigNumberish],
    [string[]],
    "view"
  >;

  getSubscriptionInfo: TypedContractMethod<
    [user: AddressLike, packageId: BigNumberish],
    [SubscriptionManager.SubscriptionStructOutput],
    "view"
  >;

  getTotalEarnings: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getUserSubscriptions: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], SubscriptionManager.SubscriptionStructOutput[]] & {
        activePackages: bigint[];
        subs: SubscriptionManager.SubscriptionStructOutput[];
      }
    ],
    "view"
  >;

  hasActiveSubscription: TypedContractMethod<
    [user: AddressLike, packageId: BigNumberish],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  packageCount: TypedContractMethod<[], [bigint], "view">;

  packages: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, boolean, bigint, bigint] & {
        id: bigint;
        title: string;
        price: bigint;
        channelCount: bigint;
        creator: string;
        active: boolean;
        subscriberCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renewSubscription: TypedContractMethod<
    [packageId: BigNumberish, durationMonths: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<
    [packageId: BigNumberish, durationMonths: BigNumberish, autoRenew: boolean],
    [void],
    "payable"
  >;

  subscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint] & {
        packageId: bigint;
        startTime: bigint;
        endTime: bigint;
        autoRenew: boolean;
        tokenId: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  togglePackageStatus: TypedContractMethod<
    [packageId: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateChannelInPackage: TypedContractMethod<
    [packageId: BigNumberish, channelIndex: BigNumberish, newChannel: string],
    [void],
    "nonpayable"
  >;

  updatePackage: TypedContractMethod<
    [
      packageId: BigNumberish,
      newTitle: string,
      newPrice: BigNumberish,
      newChannelCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdrawAllEarnings: TypedContractMethod<[], [void], "nonpayable">;

  withdrawEarnings: TypedContractMethod<
    [packageId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawTreasuryFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addChannelToPackage"
  ): TypedContractMethod<
    [packageId: BigNumberish, channel: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelAutoRenewal"
  ): TypedContractMethod<[packageId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPackage"
  ): TypedContractMethod<
    [title: string, pricePerMonth: BigNumberish, channelCount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorEarnings"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllActivePackages"
  ): TypedContractMethod<
    [],
    [SubscriptionManager.PackageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCreatorPackages"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPackageChannels"
  ): TypedContractMethod<[packageId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSubscriptionInfo"
  ): TypedContractMethod<
    [user: AddressLike, packageId: BigNumberish],
    [SubscriptionManager.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalEarnings"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserSubscriptions"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], SubscriptionManager.SubscriptionStructOutput[]] & {
        activePackages: bigint[];
        subs: SubscriptionManager.SubscriptionStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveSubscription"
  ): TypedContractMethod<
    [user: AddressLike, packageId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "packageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "packages"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, boolean, bigint, bigint] & {
        id: bigint;
        title: string;
        price: bigint;
        channelCount: bigint;
        creator: string;
        active: boolean;
        subscriberCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renewSubscription"
  ): TypedContractMethod<
    [packageId: BigNumberish, durationMonths: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [packageId: BigNumberish, durationMonths: BigNumberish, autoRenew: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint] & {
        packageId: bigint;
        startTime: bigint;
        endTime: bigint;
        autoRenew: boolean;
        tokenId: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "togglePackageStatus"
  ): TypedContractMethod<[packageId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateChannelInPackage"
  ): TypedContractMethod<
    [packageId: BigNumberish, channelIndex: BigNumberish, newChannel: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePackage"
  ): TypedContractMethod<
    [
      packageId: BigNumberish,
      newTitle: string,
      newPrice: BigNumberish,
      newChannelCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAllEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[packageId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTreasuryFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PackageCreated"
  ): TypedContractEvent<
    PackageCreatedEvent.InputTuple,
    PackageCreatedEvent.OutputTuple,
    PackageCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PackageStatusChanged"
  ): TypedContractEvent<
    PackageStatusChangedEvent.InputTuple,
    PackageStatusChangedEvent.OutputTuple,
    PackageStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "PackageUpdated"
  ): TypedContractEvent<
    PackageUpdatedEvent.InputTuple,
    PackageUpdatedEvent.OutputTuple,
    PackageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRenewed"
  ): TypedContractEvent<
    SubscriptionRenewedEvent.InputTuple,
    SubscriptionRenewedEvent.OutputTuple,
    SubscriptionRenewedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "EarningsWithdrawn(address,uint256,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PackageCreated(uint256,string,uint256,address,uint256)": TypedContractEvent<
      PackageCreatedEvent.InputTuple,
      PackageCreatedEvent.OutputTuple,
      PackageCreatedEvent.OutputObject
    >;
    PackageCreated: TypedContractEvent<
      PackageCreatedEvent.InputTuple,
      PackageCreatedEvent.OutputTuple,
      PackageCreatedEvent.OutputObject
    >;

    "PackageStatusChanged(uint256,bool)": TypedContractEvent<
      PackageStatusChangedEvent.InputTuple,
      PackageStatusChangedEvent.OutputTuple,
      PackageStatusChangedEvent.OutputObject
    >;
    PackageStatusChanged: TypedContractEvent<
      PackageStatusChangedEvent.InputTuple,
      PackageStatusChangedEvent.OutputTuple,
      PackageStatusChangedEvent.OutputObject
    >;

    "PackageUpdated(uint256,uint256,uint256)": TypedContractEvent<
      PackageUpdatedEvent.InputTuple,
      PackageUpdatedEvent.OutputTuple,
      PackageUpdatedEvent.OutputObject
    >;
    PackageUpdated: TypedContractEvent<
      PackageUpdatedEvent.InputTuple,
      PackageUpdatedEvent.OutputTuple,
      PackageUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "Subscribed(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "SubscriptionCancelled(address,uint256)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionRenewed(address,uint256,uint256)": TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
    SubscriptionRenewed: TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
